version: '3'
services:
  app:
    image: leantime/leantime:latest
    ports:
      - 80:80
    environment:
      - DB_HOST=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  db:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=SECRET
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}